# 将此文件重命名为config.yaml
# 填写前请先查阅说明文档

# 填写用户配置文件的文件名（必填）
user: "sample_user"
# 填写目标仪器设备id，同时也是表单配置文件的文件名（必填）
equipment_id: "0"
# 预约开始时间（格式：YYYY-MM-DD HH:MM:SS）（必填）
start: "2024-04-01 09:00:00"
# 预约结束时间（格式：YYYY-MM-DD HH:MM:SS）（必填）
end: "2024-04-01 09:30:00"
# 虚假的预约开始时间（格式：YYYY-MM-DD HH:MM:SS）
hackstart: ""
# 虚假的预约结束时间（格式：YYYY-MM-DD HH:MM:SS）
hackend: ""
# 添加或修改预约时使用的用户身份id，默认为当前用户
hackuser_id: ""
# 填写已经存在的组件id将会修改此预约信息，默认为空，即创建新的预约
component_id: ""
# 是否卡点发送预约请求（true/false）
schedule: true

# 以井号（#）开头的行是注释，不会被程序读取
# 请不要修改每一行的冒号前的内容
# 在每行填写信息时，除非你知道自己在做什么，否则不建议删除双引号，也不要删除冒号和引号之间的空格
