# 请根据目标仪器设备的预约表单信息修改表单内容
# 此文件的文件名应为仪器id，例如，样例文件0.yaml对应了id为0的仪器（该仪器并不存在）

# 第一个填写项（文本或单选按钮）
extra_fields[1]: "2"

# 第二个填写项（复选框）
# 其中，“选项1”、“选项2”是选项的实际标题，on是选中的状态，null是未选中的状态
# 不选的选项（即null行）可以写出，也可以省略
extra_fields[2][选项1]: "null"
extra_fields[2][选项2]: "on"
extra_fields[2][选项3]: "null"
# extra_fields[2][选项4]: "null"
# extra_fields[2][其他]: "null"

# 覆盖默认字段
description: "这是一段备注信息"

# 创建预约的最早提前时间（单位：天）
days_in_advance: 0

# 以井号（#）开头的行是注释，不会被程序读取
# 在每行填写信息时，除非你知道自己在做什么，否则不建议删除双引号，也不要删除冒号和引号之间的空格
