# 请根据目标仪器设备的预约表单信息修改表单内容
# 此文件的文件名应为仪器id，例如，样例文件0.yaml对应了id为0的仪器（该仪器并不存在）

# ============================================= 默认字段 ============================================= #
# 默认字段是指在表单中位于预约信息/样品信息下的字段
# 若要修改以下默认字段，请在修改后删除行首井号（#）以取消注释

# 主题，默认为“仪器使用预约”
#name: "仪器使用预约"

# 备注，默认为空
#description: ""

# 关联项目，默认为字符"0"，即不选
#project: "0"

# 经费卡号，默认为字符"0"，即不选
#fund_card_no: "0"

# 样品数，默认为数字1
#count: 1


# ============================================= 默认字段 ============================================= #

# ============================================= 其它字段 ============================================= #
# 其它字段是指在表单中除位于预约信息/样品信息下的其它字段
# 每个仪器的表单都不尽相同，这里仅给出一些样例，请参照文档填写

# 第一个填写项（文本框或单选按钮）
## 填写输入到文本框中的值，或选中的单选按钮的标签
extra_fields[1]: "2"

# 第二个填写项（复选框）
## 其中，“选项1”、“选项2”请更改为选项的实际标题，on是选中的状态，null是未选中的状态
## 不选的选项（即null行）可以写出，也可以省略；
extra_fields[2][选项1]: "null"
extra_fields[2][选项2]: "on"
extra_fields[2][选项3]: "null"
#extra_fields[2][选项4]: "null"
#extra_fields[2][其他]: "null"

# 第三个填写项（下拉列表）
## 填写选中的选项的编号（按从上到下的顺序，从1开始计算），填"0"则代表不选。
extra_fields[3]: "0"


# ============================================= 其它字段 ============================================= #

# ============================================ 非表单字段 ============================================ #
# 非表单字段是指在不在预约表单中出现的字段，用于控制程序的行为

# 创建预约的最早提前天数
days_in_advance: 0


# ============================================ 非表单字段 ============================================ #


# 以井号（#）开头的行是注释，不会被程序读取
# 请不要修改每一行的冒号前的内容（删除行首井号以取消注释除外）
# 在每行填写信息时，除非你知道自己在做什么，否则不建议删除双引号，也不要删除冒号和引号之间的空格
